import sys
from logging.config import fileConfig
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

# Importing app.models registers every model class on Base.metadata below —
# without this import, autogenerate would see an empty metadata and think
# every existing table needs dropping.
import app.models  # noqa: E402, F401
from alembic import context  # noqa: E402
from app.db import Base, get_database_url, get_engine  # noqa: E402

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The app's own declarative base — same metadata the app builds tables from,
# so autogenerate diffs against the real thing.
target_metadata = Base.metadata


def include_object(object, name, type_, reflected, compare_to) -> bool:
    """Exclude CHECK constraints from autogenerate's ALTER-level comparison.

    Alembic's own docs note that CHECK constraints generated by a column type
    (our Enum(..., create_constraint=True) columns) are omitted from the
    metadata side of the comparison, since they're considered part of the
    type rather than the table — but they're still picked up when Alembic
    reflects the existing database, so every one of them shows up as
    "removed" on every autogenerate run, on every table, forever. They're
    still created correctly as part of CREATE TABLE (this filter only
    affects ALTER-level diffing), so excluding them here just stops the
    false positives without losing real enforcement.
    """
    return type_ != "check_constraint"


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    context.configure(
        url=get_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    Uses the same engine-building function as the app (app.db.get_engine),
    so the connection pragmas (foreign keys, WAL, busy timeout) that apply
    to app connections apply to the migration connection too.
    """
    connectable = get_engine()

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
            include_object=include_object,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
