"""add companies and contacts

Revision ID: 4181ae73796b
Revises: fbd285589412
Create Date: 2026-08-21 17:10:28.990268

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4181ae73796b"
down_revision: str | Sequence[str] | None = "fbd285589412"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("stage", sa.String(), nullable=True),
        sa.Column("interest", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("careers_page", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("company_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("contact_mode", sa.String(), nullable=True),
        sa.Column("warmth", sa.String(), nullable=True),
        sa.Column("last_connected", sa.Date(), nullable=True),
        sa.Column("next_follow_up", sa.Date(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("hiring_companies", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contacts")
    op.drop_table("companies")
    # ### end Alembic commands ###
