"""init

Revision ID: fbd285589412
Revises:
Create Date: 2026-08-21 15:04:03.875651

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fbd285589412"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
