"""touch and stage_event tables

Revision ID: 053b691b07c4
Revises: e9cbb8f56610
Create Date: 2026-08-19 12:54:41.733463

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "053b691b07c4"
down_revision: str | Sequence[str] | None = "e9cbb8f56610"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stage_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_stage",
            sa.Enum(
                "outreach",
                "replied",
                "screen",
                "interview",
                "offer",
                "rejected",
                "ghosted",
                "withdrawn",
                "closed",
                name="stage_event_from_stage",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_stage",
            sa.Enum(
                "outreach",
                "replied",
                "screen",
                "interview",
                "offer",
                "rejected",
                "ghosted",
                "withdrawn",
                "closed",
                name="stage_event_to_stage",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["thread.id"],
            name=op.f("fk_stage_event_thread_id_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_event")),
    )
    op.create_table(
        "touch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "cold_outreach",
                "warm_intro_request",
                "referral_promised",
                "post_recruiter_call",
                "post_interview",
                "application_submitted",
                "long_term_nurture",
                name="touch_kind",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.Enum("outbound", "inbound", name="touch_direction", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "linkedin",
                "referral",
                "phone",
                "in_person",
                "portal",
                "other",
                name="touch_channel",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.Date(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["thread.id"], name=op.f("fk_touch_thread_id_thread"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_touch")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("touch")
    op.drop_table("stage_event")
    # ### end Alembic commands ###
