"""thread table

Revision ID: e9cbb8f56610
Revises: fc469eeaad0d
Create Date: 2026-08-19 12:47:56.123708

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9cbb8f56610"
down_revision: str | Sequence[str] | None = "fc469eeaad0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("role_title", sa.String(), nullable=True),
        sa.Column(
            "role_family",
            sa.Enum(
                "FDE",
                "SWE",
                "MLE",
                "MTS",
                "OTHER",
                name="thread_role_family",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "motion",
            sa.Enum(
                "cold_outreach",
                "warm_outreach",
                "cold_application",
                name="thread_motion",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "outreach",
                "replied",
                "screen",
                "interview",
                "offer",
                name="thread_stage",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "rejected",
                "ghosted",
                "withdrawn",
                "closed",
                name="thread_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "stage_entered_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("next_follow_up_date", sa.Date(), nullable=True),
        sa.Column("nudge_number", sa.Integer(), nullable=False),
        sa.Column("follow_up_pinned", sa.Boolean(), nullable=False),
        sa.Column("referral_promised", sa.Boolean(), nullable=False),
        sa.Column("referral_submitted_at", sa.Date(), nullable=True),
        sa.Column("jd_url", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.id"], name=op.f("fk_thread_company_id_company")
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contact.id"], name=op.f("fk_thread_contact_id_contact")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread")),
    )
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.create_index(
            "ix_thread_status_next_follow_up_date", ["status", "next_follow_up_date"], unique=False
        )

    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping ck_company_company_status,
    # ck_contact_contact_source, and ck_contact_contact_warmth here — a false
    # positive documented in Alembic's own docs: CHECK constraints generated
    # by a column type (our Enum(create_constraint=True) columns) are
    # excluded from the metadata side of the comparison but still picked up
    # on reflection, so they always look "removed". Removed by hand; those
    # constraints are untouched. Fixed for future migrations via
    # include_object() in env.py, added in this same commit.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.drop_index("ix_thread_status_next_follow_up_date")

    op.drop_table("thread")
    # ### end Alembic commands ###
