"""company and contact tables

Revision ID: fc469eeaad0d
Revises: 7be17b146aa2
Create Date: 2026-08-19 12:42:37.729606

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc469eeaad0d"
down_revision: str | Sequence[str] | None = "7be17b146aa2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("why_interested", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "watchlist",
                "active",
                "dormant",
                "closed",
                name="company_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company")),
    )
    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("linkedin_url", sa.String(), nullable=True),
        sa.Column(
            "warmth",
            sa.Enum("cold", "warm", "strong", name="contact_warmth", create_constraint=True),
            nullable=True,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "recruiter",
                "eng_manager",
                "friend",
                "family",
                "ex_colleague",
                "linkedin",
                "berkeley_iitk",
                "networking_event",
                "hackathon",
                "interviewed_at",
                "friend_of_friend",
                name="contact_source",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("how_we_met", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.id"], name=op.f("fk_contact_company_id_company")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contact")
    op.drop_table("company")
    # ### end Alembic commands ###
